# Host: 162.241.2.137  (Version 5.7.23-23)
# Date: 2026-02-11 07:45:02
# Generator: MySQL-Front 6.0  (Build 1.40)
USE `ereurb27_bd`;

INSERT INTO `proprietarios_tabulares` (
        `tab_tipo`,
        `id_tab_procedimento`,
        `tab_desmembramento`,
        `tab_identificado`,
        `tipo_pessoa`,
        `cpf`,
        `tab_falecido`,
        `cnpj`,
        `i_estadual`,
        `i_municipal`,
        `representante`,
        `cargo`,
        `nome`,
        `data_nasc`,
        `sexo`,
        `rg`,
        `emissor`,
        `profissao`,
        `estado_civil`,
        `uniao_estavel`,
        `telefone`,
        `celular`,
        `email`,
        `cep`,
        `logradouro`,
        `numero`,
        `complemento`,
        `bairro`,
        `cidade`,
        `estado`,
        `pai`,
        `mae`,
        `data_cadastro`,
        `data_update`,
        `status_tab`,
        `capacidade`,
        `conjuge_nome`,
        `conjuge_regime`,
        `conjuge_data_casamento`,
        `conjuge_cpf`,
        `conjuge_nasc`,
        `conjuge_sexo`,
        `conjuge_rg`,
        `conjuge_emissor`,
        `conjuge_profissao`,
        `conjuge_estado_civil`,
        `conjuge_telefone`,
        `conjuge_celular`,
        `conjuge_email`,
        `conjuge_cep`,
        `conjuge_log`,
        `conjuge_numero`,
        `conjuge_complemento`,
        `conjuge_bairro`,
        `conjuge_municipio`,
        `conjuge_estado`,
        `conjuge_pai`,
        `conjuge_mae`,
        `conjuge_update`,
        `conjuge_capacidade`
    )
VALUES (
        'Proprietário',
        '5807348143',
        'Sim',
        'Identificado',
        'Física',
        '056.462.246-08',
        'Não',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'PATRICIA IVONETE DA SILVA DOS REIS ',
        '1982-03-26',
        'Feminino',
        'MG13160817',
        'SSPMG',
        'DO LAR',
        'Casado',
        '',
        '',
        '35991833897',
        '',
        '37890000',
        'RUA JORGE CANDIDO ',
        '35',
        '',
        'BREJO ALEGRE',
        'MUZAMBINHO',
        'MG',
        'ANTONIO FRANCISCO DA SILVA',
        'SEBASTIANA MENDES DA SILVA',
        '2024-03-13 14:20',
        NULL,
        1,
        NULL,
        'ROBSON SILVEIRA DOS REIS ',
        'Comunhão parcial de bens',
        '',
        '052.531.346-03',
        '1978-08-19',
        'Masculino',
        '29.509.921-5',
        'SSPMG',
        '',
        'Casado',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '2024-03-13 14:35',
        NULL
    ),
(
        'Proprietário',
        '5807348143',
        'Sim',
        'Identificado',
        'Física',
        '046.948.358-07',
        '',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'JOSÉ DOS REIS DE MELLO ',
        '1960-12-23',
        'Masculino',
        '159289324',
        'SSPMG',
        'APOSENTADO',
        'Solteiro',
        '',
        '',
        '19993087633',
        '',
        '378900000',
        'RUA JORGE CANDIDO ',
        '25',
        '',
        'BREJO ALEGRE',
        'MUZAMBINHO ',
        'MINAS GERAIS',
        'JOAQUIM ANTONIO DE MELLO FILHO ',
        'TEREZINHA MENDES DE MELLO',
        '2024-03-22 09:52',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
(
        'Proprietário',
        '5807348143',
        'Sim',
        'Identificado',
        'Física',
        '657.590.606-00',
        'Não',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'ZILDA VIANA DE ARAUJO',
        '1967-03-02',
        'Feminino',
        '20.743.531',
        'SSPMG',
        '',
        'Casado',
        '',
        '',
        '',
        '',
        '378900000',
        'RUA JORGE CANDIDO',
        '45',
        '',
        'BREJO ALEGRE ',
        'MUZAMBINHO ',
        'MG ',
        'ANTONIO LINDOLFO DE ARAUJO ',
        'IDACI VIANA DE ARAUJO',
        '2024-03-22 10:03',
        NULL,
        1,
        NULL,
        'CARLOS ROBERTO MARTINS',
        'Comunhão parcial de bens',
        '1988-05-21',
        '622.910.256-00',
        '1963-11-27',
        'Masculino',
        'MG-3.143.985',
        'SSPMG',
        'LAVRADOR ',
        'Casado',
        '',
        '',
        '',
        '37890-000',
        'RUA JORGE CANDIDO ',
        '45',
        '',
        'BREJO ALEGRE ',
        'MUZAMBINHO ',
        'MINAS GERAIS',
        'JOSE CUSTODIO MARTINS ',
        'ANDRELINA GERALDA MARTINS ',
        '2024-03-22 10:05',
        NULL
    ),
(
        'Proprietário',
        '5807348143',
        'Sim',
        'Identificado',
        'Física',
        '523.385.176-87',
        'Não',
        '',
        '',
        '',
        '',
        '',
        'EDINEIA DIAS SEQUALINE',
        '1966-09-06',
        'Feminino',
        'M-3.829.824',
        'SSPMG',
        'DO LAR ',
        'Casado',
        'Não',
        '',
        '35998276614',
        '',
        '37890-000',
        'LINDOLFO COIMBRA ',
        '510',
        '',
        'QUINTA DA BELA VISTA',
        'MUZAMBINHO ',
        'MINAS GERAIS ',
        'NELIO NELI SEQUALINE ',
        'LUZIA DIAS SEQUALINE',
        '2024-03-25 09:49',
        '2024-10-04 14:20',
        1,
        NULL,
        'PAULO CESAR DE OLIVEIRA ',
        'Comunhão parcial de bens',
        '1996-12-15',
        '038.228.966-83',
        '1977-04-10',
        'Masculino',
        'MG-14.215.594',
        'SSPMG',
        'SERVIDOR PUBLICO ',
        'Casado',
        '',
        '(35) 99827-6614',
        '',
        '37890-000',
        'RUA LINDOLFO COIMBRA',
        '510',
        '',
        'BREJO ALEGRE ',
        'MUZAMBINHO ',
        'MINAS GERAIS ',
        'GERALDO DE OLIVEIRA ',
        'APARECIDA FLORENTINA DE OLIVEIRA',
        '2024-03-25 09:52',
        NULL
    ),
(
        'Proprietário',
        '5807348143',
        'Sim',
        'Identificado',
        'Física',
        '044.451.596-89',
        'Não',
        '',
        '',
        '',
        '',
        '',
        'CLEUZA MARQUES FERREIRA ',
        '1971-03-18',
        'Feminino',
        'MG-21.269.870',
        'POLÍCIA CIVIL MG',
        'DO LAR ',
        'Casado',
        'Não',
        '',
        '35992651864',
        '',
        '37890000',
        'RUA FRANCISCO BORGES DA COSTA',
        '850',
        '',
        'JARDIM CERAVOLO ',
        'MUZAMBINHO',
        'MINAS GERAIS ',
        'JAIRO MARQUES ',
        'CONCEICAO DE JESUS MARQUES',
        '2024-04-11 14:07',
        '2024-09-25 15:07',
        0,
        NULL,
        'ANTONIO SEBASTIAO FERREIRA ',
        'Comunhão parcial de bens',
        '1989-09-16',
        '052.411.698-90',
        '1963-09-11',
        'Masculino',
        'MG-4.876.370',
        'SSPMG',
        'LAVRADOR ',
        'Casado',
        '',
        '(35) 99265-1864',
        '',
        '37890-000',
        'RUA FRANCISCO BORGES DA COSTA ',
        '850',
        '',
        'JARDIM CERAVOLO ',
        'MUZAMBINHO ',
        'MINAS GERAIS ',
        'JOSE FERREIRA ',
        'LUIZA CANDIDA MARQUES',
        '2024-04-11 14:09',
        NULL
    ),
(
        'Proprietário',
        '5807348143',
        'Sim',
        'Identificado',
        'Física',
        '772.546.606-10',
        'Não',
        '',
        '',
        '',
        '',
        '',
        'HELENA CRISTINA MARTINS DE SOUZA',
        '1970-02-25',
        'Feminino',
        'MG-13.160.855',
        'SSPMG',
        'DO LAR',
        'Casado',
        'Não',
        '',
        '35991591529',
        '',
        '37890000',
        'RUA JORGE CÂNDIDO',
        '145',
        '',
        'QUINTA DA BELA VISTA',
        'MUZAMBINHO',
        'MINAS GERAIS',
        'JOAO CUSTODIO MARTINS ',
        'NAILDA DE SOUZA MARTINS',
        '2024-04-11 14:14',
        '2024-10-04 14:39',
        1,
        NULL,
        'ROMULO DE SOUZA',
        'Comunhão parcial de bens',
        '1990-11-24',
        '523.371.466-34',
        '1965-10-09',
        'Masculino',
        'MG-12.351.246',
        'SSPMG',
        'PEDREIRO ',
        'Casado',
        '',
        '(35) 99159-1529',
        '',
        '37890-000',
        'RUA MOURA BIANCHI ',
        '41',
        '',
        'BREJO ALEGRE',
        'MUZAMBINHO ',
        'MINAS GERAIS',
        'LAMARTINE DE SOUZA',
        'MARIA APARECIDA DE SOUZA',
        '2024-04-11 14:16',
        NULL
    ),
(
        'Proprietário',
        '5807348143',
        'Sim',
        'Identificado',
        'Física',
        '077.473.346-21',
        'Não',
        '',
        '',
        '',
        '',
        '',
        'ELAINE HELENA DAS CHAGAS DE SALES',
        '1984-02-24',
        'Feminino',
        'MG-15.575.507',
        'POLICIA CIVIL MG',
        'DO LAR',
        'Casado',
        'Não',
        '',
        '35991047987',
        '',
        '37.890.000',
        'RUA JORGE CÂNDIDO',
        '135',
        '',
        'QUINTA DA BELA VISTA',
        'MUZAMBINHO ',
        'MINAS GERAIS',
        'ANTONIO BENEDITO DAS CHAGAS',
        'ANEZIA APARECIDA DAS CHAGAS',
        '2024-04-11 14:25',
        '2024-10-04 14:33',
        1,
        NULL,
        'MAURICIO VICENTE DE SALES',
        'Comunhão parcial de bens',
        '2000-04-15',
        '014.252.226-09',
        '1978-04-21',
        'Masculino',
        'MG-8.224.408',
        'SSPMG',
        '',
        'Casado',
        '',
        '(35) 99104-7987',
        '',
        '37890-000',
        'RUA FRANCISCO BORGES DA COSTA',
        '598',
        '',
        'JARDIM CERAVOLO',
        'MUZAMBINHO',
        'MINAS GERAIS ',
        'JOAO VICENTE DE SALES',
        'CLARICE TEREZINHA DE SALES',
        '2024-04-11 14:27',
        NULL
    ),
(
        'Proprietário',
        '5807348143',
        'Sim',
        'Identificado',
        'Física',
        '109.503.556-82',
        'Não',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'RENATO DONIZETTI DA SILVA ',
        '1990-04-03',
        'Masculino',
        'MG-17.567.304',
        'SSPMG',
        'AUTONOMO',
        'Casado',
        'Não',
        '',
        '35992283494',
        '',
        '37890000',
        'RUA JORGE CANDIDO',
        '115',
        '',
        'BREJO ALEGRE ',
        'MUZAMBINHO',
        'MINAS GERAIS ',
        'JOSE ALVES DA SILVA ',
        'MARIA APARECIDA DA SILVA',
        '2024-04-11 14:34',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
(
        'Proprietário',
        '5807348143',
        'Sim',
        'Identificado',
        'Física',
        '096.506.026-82',
        'Não',
        '',
        '',
        '',
        '',
        '',
        'DANIEL VICENTE DA SILVA',
        '1988-02-12',
        'Masculino',
        'MG-16.403.764',
        'SSPMG',
        'AUXILIAR ADMINISTRATIVO ',
        'Solteiro',
        'Não',
        '',
        '35992147642',
        '',
        '37890000',
        'RUA JORGE CÂNDIDO',
        '95',
        '',
        'QUINTA DA BELA VISTA',
        'MUZAMBINHO',
        'MINAS GERAIS ',
        'JOSE ALVES DA SILVA',
        'MARIA APARECIDA DA SILVA',
        '2024-04-11 14:45',
        '2024-10-04 14:10',
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
(
        'Proprietário',
        '5807348143',
        'Sim',
        'Identificado',
        'Física',
        '150.351.578-81',
        'Não',
        '',
        '',
        '',
        '',
        '',
        'ANEZIA APARECIDA DAS CHAGAS',
        '1945-06-06',
        'Feminino',
        'MG-16.049.281',
        'POLÍCIA CIVIL MG',
        'APOSENTADA',
        'Viúvo',
        'Não',
        '',
        '35991847987',
        '',
        '378900000',
        'RUA JORGE CANDIDO',
        '85',
        '',
        'QUINTA DA BELA VISTA',
        'MUZAMBINHO ',
        'MINAS GERAIS ',
        'JOAQUIM ANTONIO DA CONCEICAO',
        'GABRIELA MARIA DE JESUS',
        '2024-04-11 15:00',
        '2024-10-04 09:16',
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
(
        'Proprietário',
        '5807348143',
        'Sim',
        'Identificado',
        'Física',
        '847.825.286-04',
        'Não',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'REGINA HELENA EUGENIO DA SILVA ',
        '1971-03-04',
        'Feminino',
        'M-4.438.424',
        'SSPMG',
        '',
        'Casado',
        'Não',
        '',
        '35992497731',
        '',
        '37890000',
        'RUA LINDOLFO COIMBRA',
        '344',
        '',
        'BREJO ALEGRE',
        'MUZAMBINHO',
        'MINAS GERAIS ',
        'JOSE EUGENIO ',
        'MARIA APARECIDA EUGENIO',
        '2024-04-11 15:04',
        NULL,
        1,
        NULL,
        'PAULO DONIZETE DA SILVA',
        'Comunhão parcial de bens',
        '1990-11-10',
        '004.073.736-59',
        '1972-08-28',
        'Masculino',
        'MG-8.801.937',
        'SSPMG',
        'CARREGADOR ARMAZEM DE CAFE',
        'Casado',
        '',
        '(35) 99249-7731',
        '',
        '37890-000',
        'RUA LINDOLFO COIMBRA',
        '344',
        '',
        'BREJO ALEGRE ',
        'MUZAMBINHO',
        'MINAS GERAIS',
        'JOSE PAULA DA SILVA ',
        'MARIA ANESIA DA SILVA',
        '2024-04-11 15:07',
        NULL
    ),
(
        'Proprietário',
        '5807348143',
        'Sim',
        'Identificado',
        'Física',
        '847.601.686-72',
        'Não',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'NILCELIO BATISTA BUENO ',
        '1972-07-07',
        'Masculino',
        'M-6.293.018',
        'SSPMG',
        'SERVIDOR PUBLICO ',
        'Solteiro',
        'Não',
        '',
        '35991838465',
        '',
        '37890000',
        'AVENIDA FRANCISCO BORGES DA COSTA ',
        '495',
        '',
        'JARDIM CERAVOLO ',
        'MUZAMBINHO',
        'MINAS GERAIS',
        'MIGUEL FERREIRA BUENO ',
        'MARIA APARECIDA BUENO ',
        '2024-04-11 15:17',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
(
        'Proprietário',
        '5807348143',
        'Sim',
        'Identificado',
        'Física',
        '034.433.976-97',
        'Não',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'MARCIA CRISTINA MAMEDIO OLIVEIRA ',
        '1978-09-17',
        'Feminino',
        'MG-11.586.474',
        'SSPMG',
        '',
        'Casado',
        'Não',
        '',
        '35991966450',
        '',
        '37890000',
        'RUA BARAO DO RIO BRANCO',
        '48',
        '',
        'CENTRO ',
        'MUZAMBINHO',
        'MG',
        'JOAO BATISTA MAMEDIO ',
        'VERA LUCIA MAMEDIO',
        '2024-04-12 09:10',
        NULL,
        1,
        NULL,
        'LEANDRO GERALDO DE OLIVEIRA',
        'Comunhão parcial de bens',
        '2016-05-14',
        '045.402.436-32',
        '1979-06-28',
        'Masculino',
        '39.504.326-8',
        'SSPMG',
        '',
        'Casado',
        '',
        '(35) 99196-6450',
        '',
        '37890-000',
        'RUA BARAO DO RIO BRANCO',
        '48',
        '',
        'CENTRO ',
        'MUZAMBINHO',
        'MG',
        'GERALDO DE OLIVEIRA ',
        'APARECIDA FLORENTINA DE OLIVEIRA ',
        '2024-04-12 09:13',
        NULL
    ),
(
        'Proprietário',
        '5807348143',
        'Sim',
        'Identificado',
        'Física',
        '499.949.136-20',
        'Não',
        '',
        '',
        '',
        '',
        '',
        'ANTONIO CARLOS BUENO ',
        '1963-12-21',
        'Masculino',
        'M-3.535.121',
        'SSPMG',
        'PEDREIRO',
        'Divorciado',
        'Não',
        '',
        '35997059686',
        '',
        '37890000',
        'RUA FRANCISCO BORGES DA COSTA',
        '630',
        '',
        'QUINTA DA BELA VISTA',
        'MUZAMBINHO ',
        'MINAS GERAIS ',
        'MIGUEL FERREIRA BUENO ',
        'MARIA APARECIDA BUENO',
        '2024-04-12 10:22',
        '2024-10-04 09:52',
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
(
        'Proprietário',
        '5807348143',
        'Sim',
        'Identificado',
        'Física',
        '064.472.966-00',
        'Não',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'LUCAS ANDERSON TAVARES',
        '1984-01-12',
        'Masculino',
        '36.957.073',
        'SSPMG',
        'AUTONOMO',
        'Solteiro',
        'Não',
        '',
        '35998432089',
        '',
        '37890000',
        'RUA JORGE CANDIDO ',
        '60',
        '',
        'BREJO ALEGRE ',
        'MUZAMBINHO',
        'MINAS GERAIS ',
        'JOSE SILVINO TAVARES ',
        'ANA MARIA ANDERSON TAVARES',
        '2024-04-12 10:31',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
(
        'Proprietário',
        '5807348143',
        'Sim',
        'Identificado',
        'Física',
        '053.767.636-84',
        'Não',
        '',
        '',
        '',
        '',
        '',
        'MICHELI BUENO FREIRE',
        '1983-10-09',
        'Feminino',
        '12.580.750',
        'SSPMG',
        '',
        'Casado',
        'Não',
        '35998039260',
        '',
        '',
        '37890000',
        'AVENIDA VEREADOR VERGILIO BARBIERI',
        '163',
        '',
        'CONJ HAB PREF SEBASTIAO DEL GAUDIO ',
        'MUZAMBINHO',
        'MINAS GERAIS',
        'SEGISFREDO OLIVEIRA FREIRE',
        'BEATRIZ BUENO FREIRE',
        '2024-04-23 15:26',
        '2024-07-24 16:37',
        1,
        NULL,
        'DANIEL GONÇALVES NEGREIRA PEON ',
        'Comunhão parcial de bens',
        '',
        '068.988.116-90',
        '1984-06-16',
        'Masculino',
        'MG12360102',
        'SSPMG',
        '',
        'Casado',
        '',
        '(35) 99803-9260',
        '',
        '37890-000',
        'AVENIDA VEREADOR VERGILIO BARBIERI',
        '163',
        '',
        'CONJ HAB PREF SEBASTIAO DEL GAUDIO ',
        'MUZAMBINHO ',
        'MINAS GERAIS ',
        'ANTONIO SILVA NEGREIRA PEON ',
        'ROSANE GONCALVES NEGREIRA PEON ',
        '2024-04-23 15:29',
        NULL
    ),
(
        'Proprietário',
        '5807348143',
        'Sim',
        'Identificado',
        'Física',
        '160.630.168-30',
        'Não',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'CLAUDINEIA FRANCISCO DA CRUZ DOMINGOS ',
        '1973-12-05',
        'Feminino',
        '265875158',
        'SSPMG',
        '',
        'Casado',
        'Não',
        '',
        '35991312507',
        '',
        '37890000',
        'RUA CANDIDO SOUZA MACHADO',
        '104',
        '',
        'JARDIM CERAVOLO',
        'MUZAMBINHO',
        'MINAS GERAIS ',
        'DAVID FRANCISCO DA CRUZ ',
        'MARIA BENEDITA FERREIRA DA SILVA',
        '2024-04-23 15:46',
        NULL,
        0,
        NULL,
        'LUCIANO CARLOS DOMINGOS ',
        'Comunhão parcial de bens',
        '2000-10-09',
        '034.036.076-31',
        '1977-06-06',
        'Masculino',
        'MG10452984',
        'SSPMG',
        '',
        'Casado',
        '',
        '(35) 99131-2507',
        '',
        '37890-000',
        'RUA CANDIDO SOUZA MACHADO',
        '104',
        '',
        'JARDIM CERAVOLO',
        'MUZAMBINHO ',
        'MINAS GERAIS ',
        'JOSE DOMINGOS ',
        'DEJANIRA MARIA JOSE',
        '2024-04-23 15:49',
        NULL
    ),
(
        'Proprietário',
        '5807348143',
        'Sim',
        'Identificado',
        'Física',
        '043.649.446-96',
        'Não',
        '',
        '',
        '',
        '',
        '',
        'ADRIANO JOSÉ DOMINGOS e LUCIANO CARLOS DOMINGOS',
        '1981-05-11',
        'Masculino',
        'MG12.068.228',
        'SSPMG',
        'AGRIGULTOR',
        'Casado',
        'Não',
        '35998719349',
        '',
        '',
        '37890000',
        'RUA JORGE CÂNDIDO',
        '125',
        '',
        'QUINTA DA BELA VISTA',
        'MUZAMBINHO',
        'MINAS GERAIS',
        'JOSÉ DOMINGOS',
        'DJANIRA MARA JOSÉ DOMINGOS',
        '2024-04-23 15:54',
        '2024-10-04 09:10',
        1,
        NULL,
        'ADRIANO JOSE DOMINGOS',
        'Comunhão parcial de bens',
        '2003-07-07',
        '043.649.446-96',
        '1981-05-11',
        'Masculino',
        'MG12068228',
        'SSPMG',
        'AGRICULTOR',
        'Casado',
        '',
        '(35) 99871-9349',
        '',
        '37890-000',
        'RUA FRANCISCO BORGES DA COSTA ',
        '226',
        '',
        'JARDIM CERAVOLO ',
        'MUZAMBINHO',
        'MINAS GERAIS ',
        'JOSE DOMINGOS',
        'DJANIRA MARIA JOSE DOMINGOS ',
        '2024-04-23 15:56',
        NULL
    ),
(
        'Proprietário',
        '5807348143',
        'Não',
        'Identificado',
        'Física',
        '',
        '',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'VANDERLEI DE FREITAS CÂNDIDO',
        '',
        'Masculino',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '37.890-000',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '2024-10-01 09:52',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    );